const char* Bloom_frag =
"#version 430 core\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform sampler2D depthTexture;\n"
"\n"
"uniform float bloomThreshold;\n"
"\n"
"void main()\n"
"{\n"
"    vec2 TexCoords = gl_FragCoord.xy / vec2(textureSize(screenTexture, 0)) * 2.0;  // Get UV from texel coords\n"
"    vec3 finalColor = texture(screenTexture, TexCoords).rgb;\n"
"\n"
"    float depth = texture(depthTexture, TexCoords).r;\n"
"\n"
"    float brightness = max(max(finalColor.r, finalColor.g), finalColor.b);\n"
"    if (depth < 1.0 && brightness > bloomThreshold) {\n"
"        FragColor = vec4(finalColor, 1.0);\n"
"    } else {\n"
"        FragColor = vec4(0.0);\n"
"    }\n"
"}\n"
;
