const char* Particles_frag =
"#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"in float vDepth;\n"
"\n"
"uniform float near;\n"
"uniform float far;\n"
"\n"
"float LinearizeDepth(float depth, float near, float far)\n"
"{\n"
"    float z = depth * 2.0 - 1.0; // Back to NDC\n"
"    return (2.0 * near * far) / (far + near - z * (far - near));\n"
"}\n"
"\n"
"void main() {\n"
"    FragColor = vec4(1.0); // Solid color (yellowish)\n"
"\n"
"    gl_FragDepth = LinearizeDepth(vDepth, near, far);\n"
"}\n"
;
