const char* Particles_vert =
"#version 330 core\n"
"\n"
"layout(location = 0) in vec3 aPos;\n"
"layout(location = 1) in vec2 aTexCoord;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"\n"
"out vec2 TexCoord;\n"
"\n"
"out float vDepth;\n"
"\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
"    TexCoord = aTexCoord;\n"
"\n"
"    vDepth = (gl_Position.z / gl_Position.w) * 0.5 + 0.5;\n"
"}\n"
;
